language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  chmod +x gradlew
script:
  ./gradlew build jacocoTestReport
notifications:
  slack: cleangallery:XPESrJkJep1O8nECLTAnebQN
after_success:
  - bash <(curl -s https://codecov.io/bash)